### ISSUE TITLE
Add css support

### ISSUE THREAD

**Issue by lonix1** [henon/TryMudBlazor#83]
It would be helpful to specify css, either inline somehow or in another tab.

**Comment by henon** [comment]
Inline is possible already. Of course in a tab would be awesome

**Comment by henon** [comment]
https://try.mudblazor.com/snippet/wYmQbuayHSfZpdvq

![image](https://user-images.githubusercontent.com/44090/193786924-c27e718d-92db-4aac-a718-1dcde2022511.png)
